import tseslint from "typescript-eslint";
// @ts-ignore -- no types for this plugin
import drizzle from "eslint-plugin-drizzle";

import {
  adapterDeepImportRestriction,
  sharedTypescriptRules,
} from "./eslint.shared.ts";

export default tseslint.config(
  {
    ignores: [
      ".deepsec/**",
      "**/.wrangler/**",
      // Generated by `wrangler types`; linting the runtime type dump is noise.
      "apps/collaboration-do/worker-configuration.d.ts",
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    plugins: {
      drizzle,
    },
    extends: [
      ...tseslint.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    rules: sharedTypescriptRules({
      canvasEngineMessage:
        "Only @drawstuff/excalidraw-adapter may depend on the canvas engine.",
    }),
  },
  {
    files: [
      "packages/excalidraw-adapter/src/**/*.{ts,tsx}",
      "packages/excalidraw-adapter/tests/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@drawstuff/collaboration",
              message:
                "The adapter cannot depend on downstream collaboration code.",
            },
            {
              name: "@drawstuff/web",
              message: "The adapter cannot depend on downstream app code.",
            },
          ],
          patterns: [
            {
              group: [
                "@drawstuff/collaboration/*",
                "@drawstuff/web/*",
                "**/apps/web/**",
              ],
              message:
                "The adapter cannot import from a downstream workspace package.",
            },
            adapterDeepImportRestriction,
          ],
        },
      ],
    },
  },
  {
    files: ["apps/collaboration-do/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@drawstuff/excalidraw-adapter",
              message:
                "The DO gateway routes protocol frames; it cannot depend on the canvas engine boundary.",
            },
            {
              name: "react",
              message: "The DO gateway is a headless service; no React.",
            },
            {
              name: "ws",
              message:
                "workerd provides WebSocket natively; the Node ws stack must not leak into the Worker.",
            },
          ],
          patterns: [
            {
              group: [
                "@drawstuff/excalidraw-adapter/*",
                "@drawstuff/web/*",
                "@excalidraw/*",
                "**/apps/web/**",
                "**/packages/excalidraw-adapter/**",
              ],
              message:
                "The DO worker may only import @drawstuff/collaboration protocol entries and Cloudflare runtime modules.",
            },
          ],
        },
      ],
    },
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
  },
);
