packages:
  - "packages/*"

enableGlobalVirtualStore: false

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"

allowBuilds:
  esbuild: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
