export const APP_ERROR = {
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND",
  SCENE_CONFLICT: "SCENE_CONFLICT",
  SCENE_ASSETS_MISSING: "SCENE_ASSETS_MISSING",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CREATE_FAILED: "CREATE_FAILED",
  SAVE_FAILED: "SAVE_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
} as const;
export type AppErrorCode = (typeof APP_ERROR)[keyof typeof APP_ERROR];
